######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 19:33:56 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
#INCLUDEPATH += /usr/include/qt4/QtWebKit
QT += webkit

# Input
HEADERS += pageprinter.h
SOURCES += main.cpp pageprinter.cpp
